/* DDL (DATA DEFINATION LANGUAGE) 5 COMMANDS OF DDL (CREATE,ALTER,SP-RENAME,TRUNCATE,DROP)
 DDL COMANDS ARE USED TO DEFINR  DATABASE OBJRCTS SUCH AS 
  TABLES 
  VIEWS
  PROCEDURES
  FUNCTIONS AND TRIGGERS 
 DDL COMMANDS ARE USED TO ALTER/MODIFY A DATABASE OR TABLE STRUCTURE AND SCHEMA
 
 CREATE COMMAND IN SQL SERVERql